// Code generated by "stringer -type=TurnFailureReason,RelayDirection -output enums.go"; DO NOT EDIT.

package stats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TurnFailureUnknown-0]
	_ = x[TurnFailureAuth-1]
	_ = x[TurnFailureAllocation-2]
	_ = x[TurnFailureCreatePermission-3]
	_ = x[TurnFailureSendIndicaton-4]
	_ = x[TurnFailureChannelBindRequest-5]
	_ = x[TurnFailureChannelData-6]
}

const _TurnFailureReason_name = "TurnFailureUnknownTurnFailureAuthTurnFailureAllocationTurnFailureCreatePermissionTurnFailureSendIndicatonTurnFailureChannelBindRequestTurnFailureChannelData"

var _TurnFailureReason_index = [...]uint8{0, 18, 33, 54, 81, 105, 134, 156}

func (i TurnFailureReason) String() string {
	if i < 0 || i >= TurnFailureReason(len(_TurnFailureReason_index)-1) {
		return "TurnFailureReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TurnFailureReason_name[_TurnFailureReason_index[i]:_TurnFailureReason_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RelayDirectionUnknown-0]
	_ = x[RelayDirectionClientToServer-1]
	_ = x[RelayDirectionServerToPeer-2]
	_ = x[RelayDirectionPeerToServer-3]
	_ = x[RelayDirectionServerToClient-4]
}

const _RelayDirection_name = "RelayDirectionUnknownRelayDirectionClientToServerRelayDirectionServerToPeerRelayDirectionPeerToServerRelayDirectionServerToClient"

var _RelayDirection_index = [...]uint8{0, 21, 49, 75, 101, 129}

func (i RelayDirection) String() string {
	if i < 0 || i >= RelayDirection(len(_RelayDirection_index)-1) {
		return "RelayDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RelayDirection_name[_RelayDirection_index[i]:_RelayDirection_index[i+1]]
}
