// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go
//
// Generated by this command:
//
//	mockgen -source=stats.go -destination=./stats_mock.go -typed -package=stats
//

// Package stats is a generated GoMock package.
package stats

import (
	reflect "reflect"
	time "time"

	stun "github.com/pion/stun/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRecorder is a mock of StatsRecorder interface.
type MockStatsRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRecorderMockRecorder
}

// MockStatsRecorderMockRecorder is the mock recorder for MockStatsRecorder.
type MockStatsRecorderMockRecorder struct {
	mock *MockStatsRecorder
}

// NewMockStatsRecorder creates a new mock instance.
func NewMockStatsRecorder(ctrl *gomock.Controller) *MockStatsRecorder {
	mock := &MockStatsRecorder{ctrl: ctrl}
	mock.recorder = &MockStatsRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRecorder) EXPECT() *MockStatsRecorderMockRecorder {
	return m.recorder
}

// AddAllocationDuration mocks base method.
func (m *MockStatsRecorder) AddAllocationDuration(realm string, d time.Duration, transport TurnTransport, ipv IPVersion) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAllocationDuration", realm, d, transport, ipv)
}

// AddAllocationDuration indicates an expected call of AddAllocationDuration.
func (mr *MockStatsRecorderMockRecorder) AddAllocationDuration(realm, d, transport, ipv any) *MockStatsRecorderAddAllocationDurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAllocationDuration", reflect.TypeOf((*MockStatsRecorder)(nil).AddAllocationDuration), realm, d, transport, ipv)
	return &MockStatsRecorderAddAllocationDurationCall{Call: call}
}

// MockStatsRecorderAddAllocationDurationCall wrap *gomock.Call
type MockStatsRecorderAddAllocationDurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderAddAllocationDurationCall) Return() *MockStatsRecorderAddAllocationDurationCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderAddAllocationDurationCall) Do(f func(string, time.Duration, TurnTransport, IPVersion)) *MockStatsRecorderAddAllocationDurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderAddAllocationDurationCall) DoAndReturn(f func(string, time.Duration, TurnTransport, IPVersion)) *MockStatsRecorderAddAllocationDurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DecActiveAllocation mocks base method.
func (m *MockStatsRecorder) DecActiveAllocation(realm string, transport TurnTransport, ipv IPVersion) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecActiveAllocation", realm, transport, ipv)
}

// DecActiveAllocation indicates an expected call of DecActiveAllocation.
func (mr *MockStatsRecorderMockRecorder) DecActiveAllocation(realm, transport, ipv any) *MockStatsRecorderDecActiveAllocationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecActiveAllocation", reflect.TypeOf((*MockStatsRecorder)(nil).DecActiveAllocation), realm, transport, ipv)
	return &MockStatsRecorderDecActiveAllocationCall{Call: call}
}

// MockStatsRecorderDecActiveAllocationCall wrap *gomock.Call
type MockStatsRecorderDecActiveAllocationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderDecActiveAllocationCall) Return() *MockStatsRecorderDecActiveAllocationCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderDecActiveAllocationCall) Do(f func(string, TurnTransport, IPVersion)) *MockStatsRecorderDecActiveAllocationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderDecActiveAllocationCall) DoAndReturn(f func(string, TurnTransport, IPVersion)) *MockStatsRecorderDecActiveAllocationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncActiveAllocation mocks base method.
func (m *MockStatsRecorder) IncActiveAllocation(realm string, transport TurnTransport, ipv IPVersion) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncActiveAllocation", realm, transport, ipv)
}

// IncActiveAllocation indicates an expected call of IncActiveAllocation.
func (mr *MockStatsRecorderMockRecorder) IncActiveAllocation(realm, transport, ipv any) *MockStatsRecorderIncActiveAllocationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncActiveAllocation", reflect.TypeOf((*MockStatsRecorder)(nil).IncActiveAllocation), realm, transport, ipv)
	return &MockStatsRecorderIncActiveAllocationCall{Call: call}
}

// MockStatsRecorderIncActiveAllocationCall wrap *gomock.Call
type MockStatsRecorderIncActiveAllocationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncActiveAllocationCall) Return() *MockStatsRecorderIncActiveAllocationCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncActiveAllocationCall) Do(f func(string, TurnTransport, IPVersion)) *MockStatsRecorderIncActiveAllocationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncActiveAllocationCall) DoAndReturn(f func(string, TurnTransport, IPVersion)) *MockStatsRecorderIncActiveAllocationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncFailedChannelData mocks base method.
func (m *MockStatsRecorder) IncFailedChannelData(realm string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailedChannelData", realm, err)
}

// IncFailedChannelData indicates an expected call of IncFailedChannelData.
func (mr *MockStatsRecorderMockRecorder) IncFailedChannelData(realm, err any) *MockStatsRecorderIncFailedChannelDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedChannelData", reflect.TypeOf((*MockStatsRecorder)(nil).IncFailedChannelData), realm, err)
	return &MockStatsRecorderIncFailedChannelDataCall{Call: call}
}

// MockStatsRecorderIncFailedChannelDataCall wrap *gomock.Call
type MockStatsRecorderIncFailedChannelDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncFailedChannelDataCall) Return() *MockStatsRecorderIncFailedChannelDataCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncFailedChannelDataCall) Do(f func(string, error)) *MockStatsRecorderIncFailedChannelDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncFailedChannelDataCall) DoAndReturn(f func(string, error)) *MockStatsRecorderIncFailedChannelDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncFailedMessage mocks base method.
func (m *MockStatsRecorder) IncFailedMessage(realm string, c StatsMessageClass, s StatsMethod, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailedMessage", realm, c, s, err)
}

// IncFailedMessage indicates an expected call of IncFailedMessage.
func (mr *MockStatsRecorderMockRecorder) IncFailedMessage(realm, c, s, err any) *MockStatsRecorderIncFailedMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedMessage", reflect.TypeOf((*MockStatsRecorder)(nil).IncFailedMessage), realm, c, s, err)
	return &MockStatsRecorderIncFailedMessageCall{Call: call}
}

// MockStatsRecorderIncFailedMessageCall wrap *gomock.Call
type MockStatsRecorderIncFailedMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockStatsRecorderIncFailedMessageCall) Return() *MockStatsRecorderIncFailedMessageCall {
	c_2.Call = c_2.Call.Return()
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockStatsRecorderIncFailedMessageCall) Do(f func(string, StatsMessageClass, StatsMethod, error)) *MockStatsRecorderIncFailedMessageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockStatsRecorderIncFailedMessageCall) DoAndReturn(f func(string, StatsMessageClass, StatsMethod, error)) *MockStatsRecorderIncFailedMessageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// IncFailedTurn mocks base method.
func (m *MockStatsRecorder) IncFailedTurn(realm string, msgType stun.MessageType, reason TurnFailureReason, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailedTurn", realm, msgType, reason, err)
}

// IncFailedTurn indicates an expected call of IncFailedTurn.
func (mr *MockStatsRecorderMockRecorder) IncFailedTurn(realm, msgType, reason, err any) *MockStatsRecorderIncFailedTurnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedTurn", reflect.TypeOf((*MockStatsRecorder)(nil).IncFailedTurn), realm, msgType, reason, err)
	return &MockStatsRecorderIncFailedTurnCall{Call: call}
}

// MockStatsRecorderIncFailedTurnCall wrap *gomock.Call
type MockStatsRecorderIncFailedTurnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncFailedTurnCall) Return() *MockStatsRecorderIncFailedTurnCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncFailedTurnCall) Do(f func(string, stun.MessageType, TurnFailureReason, error)) *MockStatsRecorderIncFailedTurnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncFailedTurnCall) DoAndReturn(f func(string, stun.MessageType, TurnFailureReason, error)) *MockStatsRecorderIncFailedTurnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncRelayBytes mocks base method.
func (m *MockStatsRecorder) IncRelayBytes(realm string, n int, dir RelayDirection, transport TurnTransport, ipv IPVersion) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRelayBytes", realm, n, dir, transport, ipv)
}

// IncRelayBytes indicates an expected call of IncRelayBytes.
func (mr *MockStatsRecorderMockRecorder) IncRelayBytes(realm, n, dir, transport, ipv any) *MockStatsRecorderIncRelayBytesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRelayBytes", reflect.TypeOf((*MockStatsRecorder)(nil).IncRelayBytes), realm, n, dir, transport, ipv)
	return &MockStatsRecorderIncRelayBytesCall{Call: call}
}

// MockStatsRecorderIncRelayBytesCall wrap *gomock.Call
type MockStatsRecorderIncRelayBytesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncRelayBytesCall) Return() *MockStatsRecorderIncRelayBytesCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncRelayBytesCall) Do(f func(string, int, RelayDirection, TurnTransport, IPVersion)) *MockStatsRecorderIncRelayBytesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncRelayBytesCall) DoAndReturn(f func(string, int, RelayDirection, TurnTransport, IPVersion)) *MockStatsRecorderIncRelayBytesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncRelayPackets mocks base method.
func (m *MockStatsRecorder) IncRelayPackets(realm string, dir RelayDirection, transport TurnTransport, ipv IPVersion) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRelayPackets", realm, dir, transport, ipv)
}

// IncRelayPackets indicates an expected call of IncRelayPackets.
func (mr *MockStatsRecorderMockRecorder) IncRelayPackets(realm, dir, transport, ipv any) *MockStatsRecorderIncRelayPacketsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRelayPackets", reflect.TypeOf((*MockStatsRecorder)(nil).IncRelayPackets), realm, dir, transport, ipv)
	return &MockStatsRecorderIncRelayPacketsCall{Call: call}
}

// MockStatsRecorderIncRelayPacketsCall wrap *gomock.Call
type MockStatsRecorderIncRelayPacketsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncRelayPacketsCall) Return() *MockStatsRecorderIncRelayPacketsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncRelayPacketsCall) Do(f func(string, RelayDirection, TurnTransport, IPVersion)) *MockStatsRecorderIncRelayPacketsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncRelayPacketsCall) DoAndReturn(f func(string, RelayDirection, TurnTransport, IPVersion)) *MockStatsRecorderIncRelayPacketsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncTotalChannelData mocks base method.
func (m *MockStatsRecorder) IncTotalChannelData(realm string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncTotalChannelData", realm)
}

// IncTotalChannelData indicates an expected call of IncTotalChannelData.
func (mr *MockStatsRecorderMockRecorder) IncTotalChannelData(realm any) *MockStatsRecorderIncTotalChannelDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncTotalChannelData", reflect.TypeOf((*MockStatsRecorder)(nil).IncTotalChannelData), realm)
	return &MockStatsRecorderIncTotalChannelDataCall{Call: call}
}

// MockStatsRecorderIncTotalChannelDataCall wrap *gomock.Call
type MockStatsRecorderIncTotalChannelDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncTotalChannelDataCall) Return() *MockStatsRecorderIncTotalChannelDataCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncTotalChannelDataCall) Do(f func(string)) *MockStatsRecorderIncTotalChannelDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncTotalChannelDataCall) DoAndReturn(f func(string)) *MockStatsRecorderIncTotalChannelDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncTotalMessage mocks base method.
func (m_2 *MockStatsRecorder) IncTotalMessage(realm string, c StatsMessageClass, m StatsMethod) {
	m_2.ctrl.T.Helper()
	m_2.ctrl.Call(m_2, "IncTotalMessage", realm, c, m)
}

// IncTotalMessage indicates an expected call of IncTotalMessage.
func (mr *MockStatsRecorderMockRecorder) IncTotalMessage(realm, c, m any) *MockStatsRecorderIncTotalMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncTotalMessage", reflect.TypeOf((*MockStatsRecorder)(nil).IncTotalMessage), realm, c, m)
	return &MockStatsRecorderIncTotalMessageCall{Call: call}
}

// MockStatsRecorderIncTotalMessageCall wrap *gomock.Call
type MockStatsRecorderIncTotalMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockStatsRecorderIncTotalMessageCall) Return() *MockStatsRecorderIncTotalMessageCall {
	c_2.Call = c_2.Call.Return()
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockStatsRecorderIncTotalMessageCall) Do(f func(string, StatsMessageClass, StatsMethod)) *MockStatsRecorderIncTotalMessageCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockStatsRecorderIncTotalMessageCall) DoAndReturn(f func(string, StatsMessageClass, StatsMethod)) *MockStatsRecorderIncTotalMessageCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// IncTotalTurn mocks base method.
func (m *MockStatsRecorder) IncTotalTurn(realm string, msgType stun.MessageType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncTotalTurn", realm, msgType)
}

// IncTotalTurn indicates an expected call of IncTotalTurn.
func (mr *MockStatsRecorderMockRecorder) IncTotalTurn(realm, msgType any) *MockStatsRecorderIncTotalTurnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncTotalTurn", reflect.TypeOf((*MockStatsRecorder)(nil).IncTotalTurn), realm, msgType)
	return &MockStatsRecorderIncTotalTurnCall{Call: call}
}

// MockStatsRecorderIncTotalTurnCall wrap *gomock.Call
type MockStatsRecorderIncTotalTurnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatsRecorderIncTotalTurnCall) Return() *MockStatsRecorderIncTotalTurnCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatsRecorderIncTotalTurnCall) Do(f func(string, stun.MessageType)) *MockStatsRecorderIncTotalTurnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatsRecorderIncTotalTurnCall) DoAndReturn(f func(string, stun.MessageType)) *MockStatsRecorderIncTotalTurnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
